---
deployment:
  tasks:
    - export DEPLOYPATH= /home/pggtlchq/public_html/project_defcon
    - /bin/cp -R .vscode $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R dashboard $DEPLOYPATH
    - /bin/cp -R backend $DEPLOYPATH
    - /bin/cp -R vue $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH